import OurOffice from "@/components/screen/ContactUs/OurOffice";

export const metadata = {
  title: "Glamcart - Contact Us Page",
  description: "Generated by Nur IT Software LTD.",
};

const ContactUsPage = () => {
  return (
    <section className="py-13 bg-backgroundPage">
      <div className="container_fluid">
        <div className="w-full xl:max-w-[1144px]">
          <div>
            <h2 className="text-heading30 sm:text-heading42 font-semibold leading-10  md:leading-[88px] text-blackPrimary">
              Get connect with us
            </h2>
            <p className="pt-2 leading-[27px] text-textBody max-w-[888px]">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
              enim ad minim veniam.
            </p>
          </div>
          <div className="pt-10 flex flex-col md:flex-row gap-8 xl:gap-[110px]">
            <div className="w-full xl:max-w-[608px]">
              <form action="#" className="space-y-6">
                <div className="space-y-3 flex flex-col">
                  <label
                    htmlFor=""
                    className="font-medium leading-6 text-contactLabel"
                  >
                    First Name
                  </label>
                  <input
                    type="text"
                    placeholder="Your First Name"
                    className="w-full xl:w-[607px] h-10 px-4 py-3 bg-white rounded-[5px] border-[1px] border-borderContact/50 outline-none placeholder:text-grayFaq placeholder:text-sm placeholder:leading-4"
                  />
                </div>
                <div className="space-y-3 flex flex-col">
                  <label
                    htmlFor=""
                    className="font-medium leading-6 text-contactLabel"
                  >
                    Last Name
                  </label>
                  <input
                    type="text"
                    placeholder="Your Last Name"
                    className="w-full xl:w-[607px] h-10 px-4 py-3 bg-white rounded-[5px] border-[1px] border-borderContact/50 outline-none placeholder:text-grayFaq placeholder:text-sm placeholder:leading-4"
                  />
                </div>
                <div className="space-y-3 flex flex-col">
                  <label
                    htmlFor=""
                    className="font-medium leading-6 text-contactLabel"
                  >
                    Email
                  </label>
                  <input
                    type="email"
                    placeholder="email@example.com"
                    className="w-full xl:w-[607px] h-10 px-4 py-3 bg-white rounded-[5px] border-[1px] border-borderContact/50 outline-none placeholder:text-grayFaq placeholder:text-sm placeholder:leading-4"
                  />
                </div>
                <div className="space-y-3 flex flex-col">
                  <label
                    htmlFor=""
                    className="font-medium leading-6 text-contactLabel"
                  >
                    Message
                  </label>
                  <textarea
                    name=""
                    id=""
                    rows="7"
                    placeholder="Write Your Message"
                    className="w-full resize-none xl:w-[607px] px-4 py-3 bg-white rounded-[5px] border-[1px] border-borderContact/50 outline-none placeholder:text-grayFaq placeholder:text-sm placeholder:leading-4"
                  ></textarea>
                </div>
                <button className="w-[190px] h-10 rounded-[3px] bg-secondary flex items-center justify-center">
                  <span className="font-medium leading-6 text-white">
                    Send Messages
                  </span>
                </button>
              </form>
            </div>
            <OurOffice />
          </div>
        </div>
      </div>
    </section>
  );
};

export default ContactUsPage;
