import AboutHero from "@/components/screen/About/AboutHero";
import OurMission from "@/components/screen/About/OurMission";

export const metadata = {
  title: "NIRVOYA - About us Page",
  description: "Generated by Nur IT Software LTD.",
};

const page = () => {
  return (
    <section className=" bg-backgroundPage">
      <AboutHero />
      <OurMission />
    </section>
  );
};

export default page;
