import WishListProduct from "@/components/screen/WishList/WishListProduct";

export const metadata = {
  title: "NIRVOYA - WishList Page",
  description: "Generated by Nur IT Software LTD.",
};
const WishListPage = () => {
  return (
    <section className="pt-11 pb-13  bg-backgroundPage">
      <div className="container_fluid">
        <WishListProduct />
      </div>
    </section>
  );
};

export default WishListPage;
