import AboutProduct from "@/components/screen/ProductDetails/AboutProduct";
import CustomerReview from "@/components/screen/ProductDetails/CustomerReview";
import ProductDetails from "@/components/screen/ProductDetails/ProductDetails";
import SliderProduct from "@/components/screen/ProductDetails/SliderProduct";
import Breadcrumb from "@/components/shared/Breadcrum/Breadcrumb";

export const metadata = {
  title: "NIRVOYA - Products Details Page",
  description: "Generated by Nur IT Software LTD.",
};

const breadcrumb = [
  { name: "Home", url: "/" },
  { name: "Men’s fashion", url: "/men-fashion" },
];

const page = () => {
  return (
    <section className="pt-14 pb-13  bg-backgroundPage">
      <div className="container_fluid">
        <Breadcrumb
          pageName="Men's Stand Collar Leather Jacket"
          breadcrumb={breadcrumb}
        />
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-10">
          <div className="h-fit">
            <SliderProduct />
          </div>
          <div>
            <AboutProduct />
          </div>
        </div>
        <div>
          <ProductDetails />
          <CustomerReview />
        </div>
      </div>
    </section>
  );
};

export default page;
