import ShippingForm from "@/components/screen/ShippingDetails/ShippingForm";
import OrderCard from "../../components/screen/ShippingDetails/OrderCard";

export const metadata = {
  title: "Glamcart - Shipping Details Page",
  description: "Generated by Nur IT Software LTD.",
};

const ShippingDetailsPage = () => {
  return (
    <section className="pt-15 pb-13  bg-backgroundPage">
      <div className="container_fluid">
        <div className="flex flex-col xl:flex-row xl:justify-between gap-7 2xl:gap-10">
          <div>
            <ShippingForm />
          </div>
          <div>
            <OrderCard />
          </div>
        </div>
      </div>
    </section>
  );
};

export default ShippingDetailsPage;
