import CardCheckout from "@/components/screen/Checkout/CardCheckout";

export const metadata = {
  title: "NIRVOYA - Check Out Page",
  description: "Generated by Nur IT Software LTD.",
};
const page = () => {
  return (
    <>
      <section className="pt-11 pb-13  bg-backgroundPage">
        <div className="container_fluid">
          <div className="flex flex-col md:flex-row md:justify-between gap-7">
            <CardCheckout />
            <div className="w-full xl:max-w-[439px] border border-red-700">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem eius
              soluta deleniti. Sed neque expedita quisquam nulla officia autem
              mollitia velit quos magnam id a ab nesciunt, harum libero
              obcaecati.
            </div>
          </div>
        </div>
      </section>
    </>
  );
};

export default page;
