import CardCheckout from "@/components/screen/Checkout/CardCheckout";

export const metadata = {
  title: "Glamcart - Check Out Page",
  description: "Generated by Nur IT Software LTD.",
};
const CheckOutPage = () => {
  return (
    <section className="pt-11 pb-13  bg-backgroundPage">
      <div className="container_fluid">
        <CardCheckout />
      </div>
    </section>
  );
};

export default CheckOutPage;
