// import Hero from "@/components/screen/Home/Hero";

import Category from "@/components/screen/Home/Category";
import Featured from "@/components/screen/Home/Featured";
import FlashDeals from "@/components/screen/Home/FlashDeals";
import Hero from "@/components/screen/Home/Hero";

export const metadata = {
  title: "Nirvoya - Home",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <Hero />
      <Category />
      <FlashDeals />

      <Featured />
    </>
  );
}
