import AllProducts from "@/components/screen/Products/AllProducts";
import ProductSidebar from "@/components/screen/Products/ProductSidebar";
import Pagination from "@/components/screen/Products/paging/Pagination";
import getAllProducts from "../../../lib/ProductsData";

export const metadata = {
  title: "NIRVOYA - Products Page",
  description: "Generated by Nur IT Software LTD.",
};

const page = async() => {
  const allProducts = await getAllProducts()
  console.log(allProducts)

  return (
    <section className="pt-10  bg-backgroundPage">
      <div className="container_fluid">
        <div className="flex gap-9 2xl:gap-14">
          <div className="hidden lg:block w-[300px]">
            <ProductSidebar />
          </div>
          <div className="w-full pt-6">
            <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4 md:gap-0">
              <p className="text-lg leading-7 text-black/50 font-medium">
                Showing <span className="text-black">20</span> of
                <span className="text-black"> 160</span> product
              </p>
              <div className="flex items-center gap-3">
                <p className="text-lg text-black/50 leading-7">Sort by:</p>
                <div className="border-[1.2px] border-grayBorder rounded-[3px] px-4 py-[7px]">
                  <select
                    name=""
                    id=""
                    className="bg-transparent outline-none text-black text-lg "
                  >
                    <option value="" selected>
                      Newest Items
                    </option>
                    <option value="">Newest Items1</option>
                    <option value="">Newest Items</option>
                  </select>
                </div>
              </div>
            </div>

            <AllProducts allProducts={allProducts}/>
            
          </div>
        </div>
      </div>
    </section>
  );
};

export default page;
