import BlogCard from "@/components/screen/Blog/BlogCard";
import BlogPaginations from "@/components/screen/Blog/BlogPaginations";
import { blogData } from "@/data/blogData";

import Link from "next/link";

export const metadata = {
  title: "Glamcart - Blog Page",
  description: "Generated by Nur IT Software LTD.",
};

const BlogPage = () => {
  return (
    <section className="py-13  bg-backgroundPage">
      <div className="container_fluid">
        {/* heading */}
        <div className="flex items-center justify-center">
          <div className="space-y-3 text-center">
            <h2 className="text-heading36 font-semibold text-black3D leading-[54px] tracking-[2%]">
              Our Awesome Articles for you
            </h2>
            <p className="leading-6 text-grayView max-w-[817px]">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eget
              risus euismod ultrices blandit vel pellentesque suscipit. Nec
              platea eu hac consequat consequat arcu hendrerit urna, mi. Erat
              neque
            </p>
          </div>
        </div>
        <Link href={"/blog-details"}>
          <div className="mt-10 grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-y-12 gap-x-7 2xl:gap-x-10">
            {blogData.map((blogData) => 
             <BlogCard blogData={blogData} key={blogData.id}/>
            )}
          </div>
        </Link>
        <BlogPaginations />
      </div>
    </section>
  );
};

export default BlogPage;
