import Comments from "@/components/screen/BlogDetails/Comments";
import LeaveCommentForm from "@/components/screen/BlogDetails/LeaveCommentForm";
import TagAndShare from "@/components/screen/BlogDetails/TagAndShare";
import Breadcrumb from "@/components/shared/Breadcrum/Breadcrumb";
import { blogDetails } from "@/data/blogDetails";
import Image from "next/image";
export const metadata = {
  title: "NIRVOYA - Blog Details Page",
  description: "Generated by Nur IT Software LTD.",
};

const breadcrumb = [
  { name: "Home", url: "/" },
  { name: "Men’s fashion", url: "/men-fashion" },
];

const BlogDetailsPage = () => {
  return (
    <section className="pt-14 pb-13  bg-backgroundPage">
      <div className="container_fluid">
        <Breadcrumb
          pageName="Everything You Need To Know About Customized Leather Jacket."
          breadcrumb={breadcrumb}
        />

        {blogDetails.map((blogDetails) => {
          return (
            <div key={blogDetails.id}>
              <h1 className="max-w-[1283px] pb-[26px] text-2xl md:text-heading30 xl:text-heading56  contactLabel font-medium leading-7 md:leading-[45px] xl:leading-[88px]">
                {blogDetails.title}
              </h1>
              <Image
                src={blogDetails.img}
                alt=""
                className="w-full h-full object-fill rounded-[8px]"
              />
              <div className="max-w-[1393px] pt-14 space-y-10 text-textBody leading-[27px]">
                {blogDetails.description.slice(0, 1).map((item, index) => (
                  <h5 key={index}>{item}</h5>
                ))}
                {blogDetails.description.slice(1, 2).map((item, index) => (
                  <h5 key={index}>{item}</h5>
                ))}
                {blogDetails.description.slice(2, 3).map((item, index) => (
                  <h5 key={index}>{item}</h5>
                ))}
                {blogDetails.description.slice(3, 4).map((item, index) => (
                  <h5 key={index}>{item}</h5>
                ))}
              </div>
            </div>
          );
        })}

        <TagAndShare />
        <Comments />
        <LeaveCommentForm />
      </div>
    </section>
  );
};

export default BlogDetailsPage;
